In [2]:
from cs231n.classifiers.convnet import *

# for auto-reloading external modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

In [3]:
# Have written a more complex model and test it here
conv_layer_configs = ConvLayerConfig()
hidden_layer_configs = HiddenLayerConfig()
model = MultipleLayerConvNet([conv_layer_configs], [hidden_layer_configs])
# Now we have the same model with ThreeLayerConvNet class

N = 50
X = np.random.randn(N, 3, 32, 32)
y = np.random.randint(10, size=N)

loss, grads = model.loss(X, y)
print 'Initial loss (no regularization): ', loss

model.reg = 0.0
loss, grads = model.loss(X, y)
print 'Initial loss (with regularization): ', loss

Initial loss (no regularization):  2.30423118733
Initial loss (with regularization):  2.30423118733


In [4]:
from cs231n.gradient_check import eval_numerical_gradient_array, eval_numerical_gradient

In [5]:
import numpy as np
def rel_error(x, y):
  """ returns relative error """
  return np.max(np.abs(x - y) / (np.maximum(1e-8, np.abs(x) + np.abs(y))))

In [6]:
num_inputs = 2
input_dim = (3, 16, 16)
reg = 0.0
num_classes = 10
X = np.random.randn(num_inputs, *input_dim)
y = np.random.randint(num_classes, size=num_inputs)
'''
model = ThreeLayerConvNet(num_filters=3, filter_size=3,
                          input_dim=input_dim, hidden_dim=7,
                          dtype=np.float64)
'''
conv_layer_config = ConvLayerConfig(num_filters=3, use_batch_norm=True)
conv_layer_config_copy = ConvLayerConfig(num_filters=4, use_batch_norm=True)
hidden_layer_config = HiddenLayerConfig(hidden_layer_dim=10, use_batch_norm=True)
hidden_layer_config_copy = HiddenLayerConfig(hidden_layer_dim=10)
#hidden_layer_config_copy_1 = HiddenLayerConfig(hidden_layer_dim=10)

model = MultipleLayerConvNet([conv_layer_config, conv_layer_config_copy], [hidden_layer_config, hidden_layer_config_copy], 
                             input_dim=input_dim, dtype=np.float64, reg=0, seed=1, init_verbose=False)

loss, grads = model.loss(X, y)
print "Initial loss: ", loss

for param_name in sorted(grads):
  f = lambda _: model.loss(X, y)[0]
  param_grad_num = eval_numerical_gradient(f, model.params[param_name], verbose=False, h=1e-5)
  e = rel_error(param_grad_num, grads[param_name])
  print '%s max relative error: %.2e' % (param_name, rel_error(param_grad_num, grads[param_name]))

Initial loss:  3.05205091658
W1 max relative error: 2.14e-04
W2 max relative error: 4.61e-07
W3 max relative error: 7.46e-04
W4 max relative error: 2.32e-09
W5 max relative error: 5.40e-09
b1 max relative error: 2.22e-03
b2 max relative error: 2.22e-03
b3 max relative error: 3.11e-07
b4 max relative error: 1.70e-09
b5 max relative error: 1.20e-10


In [7]:
from cs231n.classifiers.fc_net import *
model = FullyConnectedNet([10, 10], input_dim=3*16*16, num_classes=10,
                            weight_scale=5e-2, dtype=np.float64, seed=1)

loss, grads = model.loss(X, y)
print 'Initial loss: ', loss

for name in sorted(grads):
  f = lambda _: model.loss(X, y)[0]
  grad_num = eval_numerical_gradient(f, model.params[name], verbose=False, h=1e-5)
  print '%s relative error: %.2e' % (name, rel_error(grad_num, grads[name]))
  

The first row of W1: [ 0.08121727 -0.03058782 -0.02640859 -0.05364843  0.04327038 -0.11507693
  0.08724059 -0.03806035  0.01595195 -0.01246852]
b1: [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
The first row of W2: [ 0.05180864 -0.0083933  -0.06161278  0.04139681 -0.01018211 -0.00716189
 -0.10649454 -0.02187732 -0.03205681  0.00559647]
b2: [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
The first row of W3: [-0.0498757   0.03622802  0.0793931  -0.04122579 -0.03326454  0.01985829
  0.04512776  0.01278485 -0.08573427  0.03662613]
b3: [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
Initial loss:  2.27778515554
W1 relative error: 1.03e-04
W2 relative error: 8.52e-08
W3 relative error: 9.81e-08
b1 relative error: 1.99e-08
b2 relative error: 5.13e-09
b3 relative error: 8.12e-11


In [8]:
np.random.seed(1)
print np.random.randn(2,2)
print np.random.randn(3,5)
print np.random.randn(4,5)
print np.random.randn(2,1)
print np.random.randn(1,2)

[[ 1.62434536 -0.61175641]
 [-0.52817175 -1.07296862]]
[[ 0.86540763 -2.3015387   1.74481176 -0.7612069   0.3190391 ]
 [-0.24937038  1.46210794 -2.06014071 -0.3224172  -0.38405435]
 [ 1.13376944 -1.09989127 -0.17242821 -0.87785842  0.04221375]]
[[ 0.58281521 -1.10061918  1.14472371  0.90159072  0.50249434]
 [ 0.90085595 -0.68372786 -0.12289023 -0.93576943 -0.26788808]
 [ 0.53035547 -0.69166075 -0.39675353 -0.6871727  -0.84520564]
 [-0.67124613 -0.0126646  -1.11731035  0.2344157   1.65980218]]
[[ 0.74204416]
 [-0.19183555]]
[[-0.88762896 -0.74715829]]


In [18]:
# make a more complex model and try again
num_inputs = 2
input_dim = (3, 16, 16)
reg = 0.0
num_classes = 10
X = np.random.randn(num_inputs, *input_dim)
y = np.random.randint(num_classes, size=num_inputs)

use_batch_norm = True
filter_num = 3
hidden_dim = 20
conv_layer_config1 = ConvLayerConfig(num_filters=filter_num, pool_params=None, use_batch_norm=use_batch_norm)
conv_layer_config2 = ConvLayerConfig(num_filters=filter_num, pool_params=None, use_batch_norm=use_batch_norm)
conv_layer_config3 = ConvLayerConfig(num_filters=filter_num, pool_params=None, use_batch_norm=use_batch_norm)
conv_layer_config4 = ConvLayerConfig(num_filters=filter_num, pool_params=None, use_batch_norm=use_batch_norm)

conv_layer_config_1 = ConvLayerConfig(num_filters=filter_num, use_batch_norm=use_batch_norm)
conv_layer_config_2 = ConvLayerConfig(num_filters=filter_num, use_batch_norm=use_batch_norm)
conv_layer_config_3 = ConvLayerConfig(num_filters=filter_num, use_batch_norm=use_batch_norm)
conv_layer_config_4 = ConvLayerConfig(num_filters=filter_num, use_batch_norm=use_batch_norm)

hidden_layer_config = HiddenLayerConfig(hidden_layer_dim=hidden_dim, use_batch_norm=False)
hidden_layer_config = HiddenLayerConfig(hidden_layer_dim=hidden_dim, use_batch_norm=False)

# To add reg param here...
model = MultipleLayerConvNet([conv_layer_config_1, conv_layer_config_2, conv_layer_config_3, conv_layer_config_4], 
                             [hidden_layer_config, hidden_layer_config], input_dim=input_dim,
                             reg=1e-3, dtype=np.float64)

loss, grads = model.loss(X, y)
print "Initial loss: ", loss

for param_name in sorted(grads):
  f = lambda _: model.loss(X, y)[0]
  param_grad_num = eval_numerical_gradient(f, model.params[param_name], verbose=False, h=1e-5)
  e = rel_error(param_grad_num, grads[param_name])
  print '%s max relative error: %.2e' % (param_name, rel_error(param_grad_num, grads[param_name]))

Initial loss:  2.58216290746
W1 max relative error: 3.11e-08
W2 max relative error: 1.84e-08
W3 max relative error: 3.97e-09
W4 max relative error: 6.15e-08
W5 max relative error: 4.65e-07
W6 max relative error: 1.89e-06
W7 max relative error: 2.12e-06
b1 max relative error: 8.40e-08
b2 max relative error: 7.42e-09
b3 max relative error: 1.91e-08
b4 max relative error: 6.94e-10
b5 max relative error: 1.47e-09
b6 max relative error: 4.46e-10
b7 max relative error: 1.13e-10
