In [54]:
from cs231n.classifiers.convnet import *

# for auto-reloading external modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [55]:
# Have written a more complex model and test it here
conv_layer_configs = ConvLayerConfig()
hidden_layer_configs = HiddenLayerConfig()
model = MultipleLayerConvNet([conv_layer_configs], [hidden_layer_configs])
# Now we have the same model with ThreeLayerConvNet class

N = 50
X = np.random.randn(N, 3, 32, 32)
y = np.random.randint(10, size=N)

loss, grads = model.loss(X, y)
print 'Initial loss (no regularization): ', loss

model.reg = 0.5
loss, grads = model.loss(X, y)
print 'Initial loss (with regularization): ', loss

Initial loss (no regularization):  2.31636100138
Initial loss (with regularization):  56.217132582


In [56]:
from cs231n.gradient_check import eval_numerical_gradient_array, eval_numerical_gradient

In [57]:
import numpy as np
def rel_error(x, y):
  """ returns relative error """
  return np.max(np.abs(x - y) / (np.maximum(1e-8, np.abs(x) + np.abs(y))))

In [79]:
num_inputs = 2
input_dim = (3, 16, 16)
reg = 0.0
num_classes = 10
X = np.random.randn(num_inputs, *input_dim)
y = np.random.randint(num_classes, size=num_inputs)
'''
model = ThreeLayerConvNet(num_filters=3, filter_size=3,
                          input_dim=input_dim, hidden_dim=7,
                          dtype=np.float64)
'''
conv_layer_config = ConvLayerConfig(num_filters=3, use_batch_norm=True)
conv_layer_config_copy = ConvLayerConfig(num_filters=4, use_batch_norm=True)
hidden_layer_config = HiddenLayerConfig(hidden_layer_dim=10, use_batch_norm=True)
hidden_layer_config_copy = HiddenLayerConfig(hidden_layer_dim=10)
#hidden_layer_config_copy_1 = HiddenLayerConfig(hidden_layer_dim=10)

model = MultipleLayerConvNet([conv_layer_config, conv_layer_config_copy], [hidden_layer_config, hidden_layer_config_copy], 
                             input_dim=input_dim, dtype=np.float64, reg=0, seed=1, init_verbose=False)

loss, grads = model.loss(X, y)
print "Initial loss: ", loss

for param_name in sorted(grads):
  f = lambda _: model.loss(X, y)[0]
  param_grad_num = eval_numerical_gradient(f, model.params[param_name], verbose=False, h=1e-5)
  e = rel_error(param_grad_num, grads[param_name])
  print '%s max relative error: %.2e' % (param_name, rel_error(param_grad_num, grads[param_name]))

Initial loss:  2.21725761973
W1 max relative error: 1.66e-05
W2 max relative error: 8.08e-07
W3 max relative error: 1.79e-03
W4 max relative error: 8.98e-10
W5 max relative error: 1.38e-09
b1 max relative error: 7.23e-11
b2 max relative error: 2.22e-03
b3 max relative error: 2.22e-03
b4 max relative error: 2.80e-10
b5 max relative error: 2.12e-10


In [59]:
from cs231n.classifiers.fc_net import *
model = FullyConnectedNet([10, 10], input_dim=3*16*16, num_classes=10,
                            weight_scale=5e-2, dtype=np.float64, seed=1)

loss, grads = model.loss(X, y)
print 'Initial loss: ', loss

for name in sorted(grads):
  f = lambda _: model.loss(X, y)[0]
  grad_num = eval_numerical_gradient(f, model.params[name], verbose=False, h=1e-5)
  print '%s relative error: %.2e' % (name, rel_error(grad_num, grads[name]))
  

The first row of W1: [ 0.08121727 -0.03058782 -0.02640859 -0.05364843  0.04327038 -0.11507693
  0.08724059 -0.03806035  0.01595195 -0.01246852]
b1: [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
The first row of W2: [ 0.05180864 -0.0083933  -0.06161278  0.04139681 -0.01018211 -0.00716189
 -0.10649454 -0.02187732 -0.03205681  0.00559647]
b2: [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
The first row of W3: [-0.0498757   0.03622802  0.0793931  -0.04122579 -0.03326454  0.01985829
  0.04512776  0.01278485 -0.08573427  0.03662613]
b3: [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
Initial loss:  2.29471136551
W1 relative error: 6.00e-06
W2 relative error: 1.34e-08
W3 relative error: 2.59e-09
b1 relative error: 5.42e-09
b2 relative error: 1.00e-09
b3 relative error: 1.52e-10


In [65]:
np.random.seed(1)
print np.random.randn(2,2)
print np.random.randn(3,5)
print np.random.randn(4,5)
print np.random.randn(2,1)
print np.random.randn(1,2)

[[ 1.62434536 -0.61175641]
 [-0.52817175 -1.07296862]]
[[ 0.86540763 -2.3015387   1.74481176 -0.7612069   0.3190391 ]
 [-0.24937038  1.46210794 -2.06014071 -0.3224172  -0.38405435]
 [ 1.13376944 -1.09989127 -0.17242821 -0.87785842  0.04221375]]
[[ 0.58281521 -1.10061918  1.14472371  0.90159072  0.50249434]
 [ 0.90085595 -0.68372786 -0.12289023 -0.93576943 -0.26788808]
 [ 0.53035547 -0.69166075 -0.39675353 -0.6871727  -0.84520564]
 [-0.67124613 -0.0126646  -1.11731035  0.2344157   1.65980218]]
[[ 0.74204416]
 [-0.19183555]]
[[-0.88762896 -0.74715829]]
