In [2]:
import numpy as np
testArr = np.zeros((2,3,3))
testArr.reshape(2, -1)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [3]:
?np.prod

In [4]:
testArr1 = np.array([[1,3,2]])
testArr1.T

array([[1],
       [3],
       [2]])

In [5]:
testArr.shape

(2, 3, 3)

In [6]:
testArr1 = np.zeros((3,2))
np.dot(testArr1, testArr.reshape((2,-1)))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [7]:
?np.nditer

In [8]:
def eval_numerical_gradient(x, verbose=True, h=0.00001):
  """ 
  a naive implementation of numerical gradient of f at x 
  - f should be a function that takes a single argument
  - x is the point (numpy array) to evaluate the gradient at
  """ 

  # fx = f(x) # evaluate function value at original point
  grad = np.zeros_like(x)
  # iterate over all indexes in x
  it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
  while not it.finished:

    # evaluate function at x+h
    ix = it.multi_index
    '''
    oldval = x[ix]
    x[ix] = oldval + h # increment by h
    fxph = f(x) # evalute f(x + h)
    x[ix] = oldval - h
    fxmh = f(x) # evaluate f(x - h)
    x[ix] = oldval # restore

    # compute the partial derivative with centered formula
    grad[ix] = (fxph - fxmh) / (2 * h) # the slope
    if verbose:
      print ix, grad[ix]
    '''
    print ix
    it.iternext() # step to next dimension

  return grad

In [9]:
eval_numerical_gradient(np.array([[1,2],[3,4]]))

(0, 0)
(0, 1)
(1, 0)
(1, 1)


array([[0, 0],
       [0, 0]])

In [10]:
testA = 1,2
testB = (2,3)

In [11]:
(testA, testB)

((1, 2), (2, 3))

In [12]:
testArr1[(0,0),(1,1)]

array([ 0.,  0.])

In [13]:
?np.zeros_like

In [14]:
np.max(testArr1, axis=1, keepdims=True)

array([[ 0.],
       [ 0.],
       [ 0.]])

In [15]:
np.arange(3)

array([0, 1, 2])

In [16]:
assert 1<2, "1 should be less than 2"

In [17]:
?np.sum

In [18]:
a= {'a':1}

In [19]:
a['a']

1

In [20]:
a

{'a': 1}

In [21]:
?np.random.choice

In [22]:
np.hstack([1,2,3])

array([1, 2, 3])

In [23]:
A = np.array([1,2])
B = np.array([3,4])
C = [A, B]

In [24]:
C

[array([1, 2]), array([3, 4])]

In [25]:
np.vstack(C)

array([[1, 2],
       [3, 4]])

In [26]:
np.argmax(testArr1, axis=1)

array([0, 0, 0])

In [27]:
D = np.hstack(C)

In [28]:
B

array([3, 4])

In [29]:
A == B

array([False, False], dtype=bool)

In [30]:
D

array([1, 2, 3, 4])

In [31]:
a

{'a': 1}

In [32]:
a

{'a': 1}

In [33]:
np.array([3,4,5.0])/np.array([1,2,3])

array([ 3.        ,  2.        ,  1.66666667])

In [34]:
a['a%s' % 1] = 2

In [35]:
a

{'a': 1, 'a1': 2}

In [37]:
np.random.seed(1)
np.random.randn(1,2)

array([[ 1.62434536, -0.61175641]])

In [38]:
np.random.randn(2,3)

array([[-0.52817175, -1.07296862,  0.86540763],
       [-2.3015387 ,  1.74481176, -0.7612069 ]])

In [40]:
np.random.seed(1)
np.random.randn(1,2)

array([[ 1.62434536, -0.61175641]])

In [41]:
np.random.randn(1,2)

array([[-0.52817175, -1.07296862]])

In [42]:
np.random.seed(1)
np.random.randn(1,2)

array([[ 1.62434536, -0.61175641]])

In [43]:
np.random.randn(1,2)

array([[-0.52817175, -1.07296862]])

In [49]:
for i in xrange(0, -1, -1):
    print i

0


In [50]:
?np.std

In [52]:
a = np.array([[1, 2], [3, 6]])
np.std(a, axis=0)

array([ 1.,  2.])

In [56]:
np.var(a, axis=0)

array([ 1.,  4.])

In [57]:
np.array([1,2]) - np.array([[1,2],[3,4]])

array([[ 0,  0],
       [-2, -2]])

In [58]:
1.0/2*2

1.0

In [59]:
1-1.0/2

0.5

In [60]:
1-1/2

1

In [61]:
1.0-1.0/3

0.6666666666666667

In [62]:
2**-1

0.5

In [64]:
np.random.uniform(size=(2,2))

array([[ 0.39676747,  0.53881673],
       [ 0.41919451,  0.6852195 ]])

In [66]:
testArr.dtype

dtype('float64')

In [67]:
np.ndarray.astype

<method 'astype' of 'numpy.ndarray' objects>

In [68]:
np.random.randn(*testArr.shape)

array([[[ 0.3190391 , -0.24937038,  1.46210794],
        [-2.06014071, -0.3224172 , -0.38405435],
        [ 1.13376944, -1.09989127, -0.17242821]],

       [[-0.87785842,  0.04221375,  0.58281521],
        [-1.10061918,  1.14472371,  0.90159072],
        [ 0.50249434,  0.90085595, -0.68372786]]])

In [69]:
?np.random.randn

In [71]:
testArr.shape

(2, 3, 3)

In [72]:
a,b,c = testArr.shape

In [73]:
a

2

In [77]:
testArr[0, :, :]

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [78]:
np.zeros((1,2))

array([[ 0.,  0.]])

In [79]:
?np.dot

In [84]:
testArr.ravel()

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.])

In [94]:
a=[[[1,2],[3,4]],[[4,5], [6,7]]]
np.pad(a, ((0,0),(1,1),(1,1)), mode='constant', constant_values=0)

array([[[0, 0, 0, 0],
        [0, 1, 2, 0],
        [0, 3, 4, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 4, 5, 0],
        [0, 6, 7, 0],
        [0, 0, 0, 0]]])

In [91]:
np.array(a).shape

(2,)

In [95]:
?np.dot

In [96]:
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,6)
c = np.tensordot(a,b, axes=([1],[0]))

In [98]:
c.shape

(3, 5, 6)

In [99]:
c

array([[[  420.,   450.,   480.,   510.,   540.,   570.],
        [  456.,   490.,   524.,   558.,   592.,   626.],
        [  492.,   530.,   568.,   606.,   644.,   682.],
        [  528.,   570.,   612.,   654.,   696.,   738.],
        [  564.,   610.,   656.,   702.,   748.,   794.]],

       [[ 1140.,  1250.,  1360.,  1470.,  1580.,  1690.],
        [ 1176.,  1290.,  1404.,  1518.,  1632.,  1746.],
        [ 1212.,  1330.,  1448.,  1566.,  1684.,  1802.],
        [ 1248.,  1370.,  1492.,  1614.,  1736.,  1858.],
        [ 1284.,  1410.,  1536.,  1662.,  1788.,  1914.]],

       [[ 1860.,  2050.,  2240.,  2430.,  2620.,  2810.],
        [ 1896.,  2090.,  2284.,  2478.,  2672.,  2866.],
        [ 1932.,  2130.,  2328.,  2526.,  2724.,  2922.],
        [ 1968.,  2170.,  2372.,  2574.,  2776.,  2978.],
        [ 2004.,  2210.,  2416.,  2622.,  2828.,  3034.]]])

In [101]:
zip(xrange(2), xrange(2))

[(0, 0), (1, 1)]