In [2]:
import numpy as np
testArr = np.zeros((2,3,3))
testArr.reshape(2, -1)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [3]:
?np.prod

In [4]:
testArr1 = np.array([[1,3,2]])
testArr1.T

array([[1],
       [3],
       [2]])

In [5]:
testArr.shape

(2, 3, 3)

In [6]:
testArr1 = np.zeros((3,2))
np.dot(testArr1, testArr.reshape((2,-1)))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [7]:
?np.nditer

In [8]:
def eval_numerical_gradient(x, verbose=True, h=0.00001):
  """ 
  a naive implementation of numerical gradient of f at x 
  - f should be a function that takes a single argument
  - x is the point (numpy array) to evaluate the gradient at
  """ 

  # fx = f(x) # evaluate function value at original point
  grad = np.zeros_like(x)
  # iterate over all indexes in x
  it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
  while not it.finished:

    # evaluate function at x+h
    ix = it.multi_index
    '''
    oldval = x[ix]
    x[ix] = oldval + h # increment by h
    fxph = f(x) # evalute f(x + h)
    x[ix] = oldval - h
    fxmh = f(x) # evaluate f(x - h)
    x[ix] = oldval # restore

    # compute the partial derivative with centered formula
    grad[ix] = (fxph - fxmh) / (2 * h) # the slope
    if verbose:
      print ix, grad[ix]
    '''
    print ix
    it.iternext() # step to next dimension

  return grad

In [9]:
eval_numerical_gradient(np.array([[1,2],[3,4]]))

(0, 0)
(0, 1)
(1, 0)
(1, 1)


array([[0, 0],
       [0, 0]])

In [10]:
testA = 1,2
testB = (2,3)

In [11]:
(testA, testB)

((1, 2), (2, 3))

In [12]:
testArr1[(0,0),(1,1)]

array([ 0.,  0.])

In [13]:
?np.zeros_like

In [14]:
np.max(testArr1, axis=1, keepdims=True)

array([[ 0.],
       [ 0.],
       [ 0.]])

In [15]:
np.arange(3)

array([0, 1, 2])

In [16]:
assert 1<2, "1 should be less than 2"

In [17]:
?np.sum

In [18]:
a= {'a':1}

In [19]:
a['a']

1

In [20]:
a

{'a': 1}

In [21]:
?np.random.choice

In [22]:
np.hstack([1,2,3])

array([1, 2, 3])

In [23]:
A = np.array([1,2])
B = np.array([3,4])
C = [A, B]

In [24]:
C

[array([1, 2]), array([3, 4])]

In [25]:
np.vstack(C)

array([[1, 2],
       [3, 4]])

In [26]:
np.argmax(testArr1, axis=1)

array([0, 0, 0])

In [27]:
D = np.hstack(C)

In [28]:
B

array([3, 4])

In [29]:
A == B

array([False, False], dtype=bool)

In [30]:
D

array([1, 2, 3, 4])

In [31]:
a

{'a': 1}

In [32]:
a

{'a': 1}

In [33]:
np.array([3,4,5.0])/np.array([1,2,3])

array([ 3.        ,  2.        ,  1.66666667])

In [34]:
a['a%s' % 1] = 2

In [35]:
a

{'a': 1, 'a1': 2}

In [37]:
np.random.seed(1)
np.random.randn(1,2)

array([[ 1.62434536, -0.61175641]])

In [38]:
np.random.randn(2,3)

array([[-0.52817175, -1.07296862,  0.86540763],
       [-2.3015387 ,  1.74481176, -0.7612069 ]])

In [40]:
np.random.seed(1)
np.random.randn(1,2)

array([[ 1.62434536, -0.61175641]])

In [41]:
np.random.randn(1,2)

array([[-0.52817175, -1.07296862]])

In [42]:
np.random.seed(1)
np.random.randn(1,2)

array([[ 1.62434536, -0.61175641]])

In [43]:
np.random.randn(1,2)

array([[-0.52817175, -1.07296862]])

In [49]:
for i in xrange(0, -1, -1):
    print i

0
