In [1]:
import numpy as np

In [2]:
?np.flatnonzero

In [3]:
?np.ndarray.transpose

In [4]:
?np.concatenate

In [5]:
testArr = np.array([[1,2],[3,4]])

In [6]:
testArr[1][1]

4

In [7]:
testArr[1,0]

3

In [8]:
testArr[:, 0]

array([1, 3])

In [9]:
np.sum(np.square(testArr))

30

In [10]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [11]:
testArr[0]

array([1, 2])

In [12]:
testArr[1]

array([3, 4])

In [13]:
testArr - testArr[0]

array([[0, 0],
       [2, 2]])

In [14]:
np.sum(testArr, axis=1)

array([3, 7])

In [15]:
np.sqrt(testArr)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [16]:
zip([1,2], [3,4])

[(1, 3), (2, 4)]

In [17]:
zip([1,2,3], [[1,2], [3,4]])

[(1, [1, 2]), (2, [3, 4])]

In [18]:
testArr ** 2

array([[ 1,  4],
       [ 9, 16]])

In [19]:
x1 = np.array([1, 2, 3, 4, 5])

In [20]:
x1_new = x1[:, np.newaxis]
x1_new

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [21]:
x2 = [1,2,3]
x1_new - x2

array([[ 0, -1, -2],
       [ 1,  0, -1],
       [ 2,  1,  0],
       [ 3,  2,  1],
       [ 4,  3,  2]])

In [22]:
np.sqrt(np.sum(np.square(x1_new - x2), axis=1))

array([ 2.23606798,  1.41421356,  2.23606798,  3.74165739,  5.38516481])

In [23]:
testArr

array([[1, 2],
       [3, 4]])

In [24]:
testArr[:, np.newaxis]

array([[[1, 2]],

       [[3, 4]]])

In [25]:
testArr[:, np.newaxis] - np.array([[1,2],[2,3], [3,4]])

array([[[ 0,  0],
        [-1, -1],
        [-2, -2]],

       [[ 2,  2],
        [ 1,  1],
        [ 0,  0]]])

In [26]:
testArr.T

array([[1, 3],
       [2, 4]])

In [27]:
testArr1 = np.array([1,2,3])

In [28]:
testArr1.T

array([1, 2, 3])

In [29]:
np.sum(testArr, axis=1)

array([3, 7])

In [30]:
np.matrix(testArr1)

matrix([[1, 2, 3]])

In [31]:
np.matrix(testArr1).T

matrix([[1],
        [2],
        [3]])

In [32]:
testArr + np.array([[1],[2]])

array([[2, 3],
       [5, 6]])

In [33]:
testArr1.transpose()

array([1, 2, 3])

In [34]:
testArr1.reshape(3,1)

array([[1],
       [2],
       [3]])

In [35]:
-1*testArr + np.array([1,2])

array([[ 0,  0],
       [-2, -2]])

In [36]:
?np.argsort

In [37]:
np.argsort(testArr)

array([[0, 1],
       [0, 1]])

In [38]:
np.argsort(np.array([[1,2],[3,2],[3,4]]))

array([[0, 1],
       [1, 0],
       [0, 1]])

In [39]:
testArr[0][np.array([1,0])]

array([2, 1])

In [40]:
a = np.array([1,2,3,1,2,2,1,1,3,2,2,1,8])
counts = np.bincount(a)
counts

array([0, 5, 5, 2, 0, 0, 0, 0, 1])

In [41]:
counts.argmax()

1

In [42]:
testArr1 = np.array([1,2,3,4])
testArr1[:2]

array([1, 2])

In [43]:
?np.array_split

In [44]:
?np.split

In [45]:
testArr

array([[1, 2],
       [3, 4]])

In [46]:
testArr = np.array([[1,2],[3,4],[5,6]])
testArr[[0,2]]

array([[1, 2],
       [5, 6]])

In [47]:
testArr[~np.array([0,2])]

array([[5, 6],
       [1, 2]])

In [48]:
?np.concatenate

In [49]:
testArr[:0]

array([], shape=(0, 2), dtype=int64)

In [50]:
np.average([1,2,4])

2.3333333333333335

In [51]:
a = [2,1]

In [52]:
a.append([1,2])

In [53]:
a

[2, 1, [1, 2]]

In [54]:
?np.vstack

In [55]:
?np.hstack

In [56]:
?np.linalg.norm

In [57]:
range(4,5)

[4]

In [58]:
?np.reshape

In [59]:
?np.ndarray.reshape

In [60]:
testArr = np.array([[1,2], [2,3], [3,4]])

In [61]:
testArr*testArr

array([[ 1,  4],
       [ 4,  9],
       [ 9, 16]])

In [62]:
?np.dot

In [63]:
a = np.zeros((2,2), dtype=np.int)
a[:,0] = np.ones((1,2), dtype=np.int)

In [64]:
np.sum(a)

2

In [65]:
?np.sum

In [66]:
testArr[(1,1), (0,0)]

array([2, 2])

In [67]:
testArr

array([[1, 2],
       [2, 3],
       [3, 4]])

In [68]:
test1dArr = np.array([1,3,5])

In [69]:
enumerate(test1dArr)

In [70]:
for idx, a in enumerate(test1dArr):
    print idx, a

0 1
1 3
2 5


In [71]:
np.vstack([1,3,5])

array([[1],
       [3],
       [5]])

In [72]:
np.maximum(testArr,2)

array([[2, 2],
       [2, 3],
       [3, 4]])

In [73]:
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [74]:
np.array(testArr > 0, dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [75]:
testArr

array([[1, 2],
       [2, 3],
       [3, 4]])

In [76]:
np.sum(testArr, axis=1)

array([3, 5, 7])

In [77]:
?np.random.choice

In [78]:
np.random.choice(10, 3)

array([0, 1, 8])

In [79]:
testArr

array([[1, 2],
       [2, 3],
       [3, 4]])

In [80]:
np.linalg.norm(testArr, axis=0)

array([ 3.74165739,  5.38516481])

In [81]:
np.argmax(testArr, axis=0)

array([2, 2])

In [82]:
np.sum(testArr > 1, axis=1)

array([1, 2, 2])

In [83]:
np.average(np.array([1,2,2]) != np.array([1,2,3]))

0.33333333333333331

In [84]:
?np.random.seed

In [85]:
?np.random.randn

In [86]:
np.random.seed(10)
W = np.random.randn(3073, 10) * 0.0001 
print W[:, 1]

[  7.15278974e-05   1.20303737e-04  -1.74337230e-04 ...,  -1.82399864e-07
  -8.23837435e-05  -1.55212930e-05]


In [87]:
np.random.seed(10)
W = np.random.randn(3073, 10) * 0.0001 
print W[:, 1]

[  7.15278974e-05   1.20303737e-04  -1.74337230e-04 ...,  -1.82399864e-07
  -8.23837435e-05  -1.55212930e-05]


In [88]:
aaa = {}
aaa["1"] = (1,2)

In [89]:
aaa["1"]

(1, 2)

In [90]:
a = 6.6e3

In [91]:
a

6600.0

In [92]:
np.log(1)

0.0

In [93]:
np.exp([1,2])

array([ 2.71828183,  7.3890561 ])

In [94]:
testArr

array([[1, 2],
       [2, 3],
       [3, 4]])

In [95]:
1e8 * 1e8 * 2.0

2e+16

In [96]:
testArr1 = testArr[1]

In [97]:
testArr1

array([2, 3])

In [98]:
np.max(testArr1)

3

In [99]:
np.max(testArr)

4

In [100]:
np.power(testArr, 2)

array([[ 1,  4],
       [ 4,  9],
       [ 9, 16]])

In [101]:
?np.power

In [102]:
?np.normalize

Object `np.normalize` not found.


In [103]:
np.linalg.norm(testArr, axis=1)

array([ 2.23606798,  3.60555128,  5.        ])

In [104]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [105]:
np.sum(testArr, axis =1)

array([3, 5, 7])

In [106]:
y = np.array([1,4,5])
np.max(y)

5

In [110]:
a = np.array([1,2])
a.dot(np.ones((2,1)))

array([ 3.])

In [120]:
np.dot(np.ones((3,2)), a.reshape((2,1)))

array([[ 3.],
       [ 3.],
       [ 3.]])

In [115]:
a.shape[0]

2

In [122]:
a.T

array([1, 2])

In [123]:
sum_factor = np.ones((3, 1))

In [124]:
sum_factor.T

array([[ 1.,  1.,  1.]])