In [95]:
import numpy as np

In [96]:
?np.flatnonzero

In [97]:
?np.ndarray.transpose

In [98]:
?np.concatenate

In [99]:
testArr = np.array([[1,2],[3,4]])

In [100]:
testArr[1][1]

4

In [101]:
testArr[1,0]

3

In [102]:
testArr[:, 0]

array([1, 3])

In [103]:
np.sum(np.square(testArr))

30

In [104]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [105]:
testArr[0]

array([1, 2])

In [106]:
testArr[1]

array([3, 4])

In [107]:
testArr - testArr[0]

array([[0, 0],
       [2, 2]])

In [108]:
np.sum(testArr, axis=1)

array([3, 7])

In [109]:
np.sqrt(testArr)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [110]:
zip([1,2], [3,4])

[(1, 3), (2, 4)]

In [111]:
zip([1,2,3], [[1,2], [3,4]])

[(1, [1, 2]), (2, [3, 4])]

In [112]:
testArr ** 2

array([[ 1,  4],
       [ 9, 16]])

In [113]:
x1 = np.array([1, 2, 3, 4, 5])

In [114]:
x1_new = x1[:, np.newaxis]
x1_new

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [115]:
x2 = [1,2,3]
x1_new - x2

array([[ 0, -1, -2],
       [ 1,  0, -1],
       [ 2,  1,  0],
       [ 3,  2,  1],
       [ 4,  3,  2]])

In [116]:
np.sqrt(np.sum(np.square(x1_new - x2), axis=1))

array([ 2.23606798,  1.41421356,  2.23606798,  3.74165739,  5.38516481])

In [117]:
testArr

array([[1, 2],
       [3, 4]])

In [118]:
testArr[:, np.newaxis]

array([[[1, 2]],

       [[3, 4]]])

In [119]:
testArr[:, np.newaxis] - np.array([[1,2],[2,3], [3,4]])

array([[[ 0,  0],
        [-1, -1],
        [-2, -2]],

       [[ 2,  2],
        [ 1,  1],
        [ 0,  0]]])

In [120]:
testArr.T

array([[1, 3],
       [2, 4]])

In [121]:
testArr1 = np.array([1,2,3])

In [122]:
testArr1.T

array([1, 2, 3])

In [123]:
np.sum(testArr, axis=1)

array([3, 7])

In [124]:
np.matrix(testArr1)

matrix([[1, 2, 3]])

In [125]:
np.matrix(testArr1).T

matrix([[1],
        [2],
        [3]])

In [126]:
testArr + np.array([[1],[2]])

array([[2, 3],
       [5, 6]])

In [127]:
testArr1.transpose()

array([1, 2, 3])

In [128]:
testArr1.reshape(3,1)

array([[1],
       [2],
       [3]])

In [129]:
-1*testArr + np.array([1,2])

array([[ 0,  0],
       [-2, -2]])

In [130]:
?np.argsort

In [131]:
np.argsort(testArr)

array([[0, 1],
       [0, 1]])

In [132]:
np.argsort(np.array([[1,2],[3,2],[3,4]]))

array([[0, 1],
       [1, 0],
       [0, 1]])

In [133]:
testArr[0][np.array([1,0])]

array([2, 1])

In [134]:
a = np.array([1,2,3,1,2,2,1,1,3,2,2,1,8])
counts = np.bincount(a)
counts

array([0, 5, 5, 2, 0, 0, 0, 0, 1])

In [135]:
counts.argmax()

1

In [136]:
testArr1 = np.array([1,2,3,4])
testArr1[:2]

array([1, 2])

In [137]:
?np.array_split

In [138]:
?np.split

In [139]:
testArr

array([[1, 2],
       [3, 4]])

In [140]:
testArr = np.array([[1,2],[3,4],[5,6]])
testArr[[0,2]]

array([[1, 2],
       [5, 6]])

In [141]:
testArr[~np.array([0,2])]

array([[5, 6],
       [1, 2]])

In [142]:
?np.concatenate

In [143]:
testArr[:0]

array([], shape=(0, 2), dtype=int64)

In [144]:
np.average([1,2,4])

2.3333333333333335

In [145]:
a = [2,1]

In [146]:
a.append([1,2])

In [147]:
a

[2, 1, [1, 2]]

In [148]:
?np.vstack

In [149]:
?np.hstack

In [150]:
?np.linalg.norm

In [151]:
range(4,5)

[4]

In [152]:
?np.reshape

In [153]:
?np.ndarray.reshape

In [154]:
testArr = np.array([[1,2], [2,3], [3,4]])

In [155]:
testArr*testArr

array([[ 1,  4],
       [ 4,  9],
       [ 9, 16]])

In [156]:
?np.dot

In [157]:
a = np.zeros((2,2), dtype=np.int)
a[:,0] = np.ones((1,2), dtype=np.int)

In [158]:
np.sum(a)

2

In [159]:
?np.sum

In [160]:
testArr[(1,1), (0,0)]

array([2, 2])

In [161]:
testArr

array([[1, 2],
       [2, 3],
       [3, 4]])

In [162]:
test1dArr = np.array([1,3,5])

In [163]:
enumerate(test1dArr)

In [164]:
for idx, a in enumerate(test1dArr):
    print idx, a

0 1
1 3
2 5


In [165]:
np.vstack([1,3,5])

array([[1],
       [3],
       [5]])

In [166]:
np.maximum(testArr,2)

array([[2, 2],
       [2, 3],
       [3, 4]])

In [167]:
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [168]:
np.array(testArr > 0, dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [169]:
testArr

array([[1, 2],
       [2, 3],
       [3, 4]])

In [170]:
np.sum(testArr, axis=1)

array([3, 5, 7])

In [171]:
?np.random.choice

In [172]:
np.random.choice(10, 3)

array([6, 0, 8])

In [173]:
testArr

array([[1, 2],
       [2, 3],
       [3, 4]])

In [174]:
np.linalg.norm(testArr, axis=0)

array([ 3.74165739,  5.38516481])

In [175]:
np.argmax(testArr, axis=0)

array([2, 2])

In [176]:
np.sum(testArr > 1, axis=1)

array([1, 2, 2])

In [177]:
np.average(np.array([1,2,2]) != np.array([1,2,3]))

0.33333333333333331

In [178]:
?np.random.seed

In [179]:
?np.random.randn

In [180]:
np.random.seed(10)
W = np.random.randn(3073, 10) * 0.0001 
print W[:, 1]

[  7.15278974e-05   1.20303737e-04  -1.74337230e-04 ...,  -1.82399864e-07
  -8.23837435e-05  -1.55212930e-05]


In [181]:
np.random.seed(10)
W = np.random.randn(3073, 10) * 0.0001 
print W[:, 1]

[  7.15278974e-05   1.20303737e-04  -1.74337230e-04 ...,  -1.82399864e-07
  -8.23837435e-05  -1.55212930e-05]


In [182]:
aaa = {}
aaa["1"] = (1,2)

In [183]:
aaa["1"]

(1, 2)

In [184]:
a = 6.6e3

In [185]:
a

6600.0

In [186]:
np.log(1)

0.0

In [187]:
np.exp([1,2])

array([ 2.71828183,  7.3890561 ])

In [188]:
testArr

array([[1, 2],
       [2, 3],
       [3, 4]])

In [207]:
1e8 * 1e8 * 2.0

2e+16

In [196]:
testArr1 = testArr[1]

In [197]:
testArr1

array([2, 3])

In [198]:
np.max(testArr1)

3

In [200]:
np.max(testArr)

4

In [208]:
np.power(testArr, 2)

array([[ 1,  4],
       [ 4,  9],
       [ 9, 16]])

In [211]:
?np.power

In [215]:
?np.normalize

Object `np.normalize` not found.


In [217]:
np.linalg.norm(testArr, axis=1)

array([ 2.23606798,  3.60555128,  5.        ])

In [218]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])